[tool.poetry]
name = "tv_schedule"
version = "0.1.0"
description = ""
authors = ["araki777 <arakichi777@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.10"
bs4 = "^0.0.1"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
selenium = "^4.11.2"
azure-functions = "^1.20.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
